// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionsList: typeof import('./components/ActionsList.vue')['default']
    Content: typeof import('./layouts/components/Content.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./layouts/components/Footer.vue')['default']
    Header: typeof import('./layouts/components/Header.vue')['default']
    MaterialLIst: typeof import('./components/MaterialLIst.vue')['default']
    Menu: typeof import('./layouts/components/Menu.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
